# Generated by Django 4.0.4 on 2022-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
