# Generated by Django 4.0.4 on 2022-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_place_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name_arabic',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='statue',
            old_name='name_arabic',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='place',
            name='display_name_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statue',
            name='display_name_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
